[tool.black]
line-length = 99
skip-string-normalization = true
exclude = '''
(
    migrations
    | .mypy_cache
    | .pytest_cache
    | .tox
    | build
    | dist
    | venv
)
'''

[tool.isort]
profile = 'black'
multi_line_output = 3
line_length = 99
include_trailing_comma = true
use_parentheses = true

[tool.mypy]
python_version = '3.12'
warn_return_any = true
warn_unused_configs = true

[[tool.mypy.overrides]]
module = ['pyodbc', 'openpyxl', 'pandas']
ignore_missing_imports = true

